# Generated by Django 2.1 on 2018-08-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='data',
            field=models.FileField(upload_to=''),
        ),
    ]
