# Generated by Django 2.1 on 2018-08-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_auto_20180812_1747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Page',
        ),
    ]
