# Generated by Django 2.1 on 2018-08-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_auto_20180812_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='number',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
