# Generated by Django 2.1 on 2018-08-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0005_page_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='data',
            field=models.BinaryField(),
        ),
    ]
